# Site settings
title: Assorted Musings
email: frasermince@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts about Ruby, Rails, Haskell, Javascript, startups, and development in general.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fraser_mince
github_username:  frasermince

# Build settings
markdown: kramdown
